const ACTIVITY_STATUS = {
    ACTIVITY_STATUS_REGISTRATION: 1,
    ACTIVITY_STATUS_REGISTRATION_TEXT: 'registration',
    ACTIVITY_STATUS_ACTIVE: 2,
    ACTIVITY_STATUS_ACTIVE_TEXT: 'active',
    ACTIVITY_STATUS_PENDING: 3,
    ACTIVITY_STATUS_PENDING_TEXT: 'pending',
    ACTIVITY_STATUS_CLOSED: 4,
    ACTIVITY_STATUS_CLOSED_TEXT: 'closed',
}

export {ACTIVITY_STATUS}
